### ISSUE TITLE
Bug: Error: unrecognized arguments

### ISSUE THREAD

**Issue by SimonB97** [Cyclenerd/google-cloud-litellm-proxy#2]
Hi Nils, i'm trying to follow your tutorial for the LLM proxy, but failed at step 5:

```
ERROR: (gcloud.builds.submit) unrecognized arguments: --service-account=projects/<my_project_id_here>/serviceAccounts/<some_long_number_here> (did you mean '--impersonate-service-account'?)
```

I'm not very familiar with GCP so I was unable to solve it myself (and since GCP-docs are a nightmare).

Would appreciate it if you could help me out!

**Comment by Cyclenerd** [comment]
No, the argument `--service-account` is correct: https://cloud.google.com/sdk/gcloud/reference/builds/submit#--service-account

Maybe you have an old version of the Google CLI installed.

**Comment by SimonB97** [comment]
I used the provided Google Cloud shell editor link from the readme file, and I can't update the Google CLI there by default measures, so I'm guessing the problem might stem from somewhere else?
